version: '3.0'
services:
  mysql_database:
    image: mysql:latest
    container_name: database
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=test
    volumes:
      - ./data:/var/lib/mysql
