version: '3.0'
services:
  database:
    image: mysql:latest
    container_name: mysql_database
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=test
    volumes:
      - ./data:/var/lib/mysql
